auto: true
pygments: true
server: true
markdown: rdiscount
permalink: /:categories/:title
columnist:
  paths:
  - _posts
baseurl: /learnosm
rdiscount:
  extensions: [smart]
translations:
  en:
    tagline: "Learn OpenStreetMap Step-by-Step"
    contribute: "Help us improve our guides!"
  bi:
    tagline:"Pelajari OpenStreetMap Langkah-Langkah"
    contribute: "Bantu kami meningkatkan pemandu kami!"
  jp:
    tagline:"OpenStreetMapはステップバイステップを学ぶ"
    contribute: "私たちは私たちのガイドを拡充する!"
  es:
    tagline: "Aprende OpenStreetMap Paso a Paso"
    contribute: "Nos ayudan a mejorar nuestros guías"