auto: true
pygments: true
server: true
markdown: rdiscount
permalink: /:categories/:title
columnist:
  paths:
  - _posts
baseurl: /learnosm
rdiscount:
  extensions: [smart]
translations:
  en:
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    proceed: "proceed to next chapter"
  bi:
    tagline: "Pelajari OpenStreetMap Langkah-Langkah"
    contribute: "Bantu kami meningkatkan pemandu kami!"
    trainingspan: "Apakah Anda seorang organizer lokakarya?"
    training: "Memeriksa materi pelatihan untuk panduan ini (dalam bahasa Inggris)"
    feedbackspan: "Apakah pasal ini bermanfaat?"
    feedback: "Beritahu kami dan membantu kami memperbaiki panduan!"
    proceed: "lanjutkan ke bab berikutnya"
  jp:
    tagline: "OpenStreetMapはステップバイステップを学ぶ"
    contribute: "私たちは私たちのガイドを拡充する!"
    trainingspan: "あなたは、このワークショップの主催者ですか?"
    training: "このガイドの研修教材をチェック(英語で)"
    feedbackspan: "この章では役に立ちましたか?"
    feedback: "私たちが知っている、私たちはガイドを改善するお手伝いをさせて!"
    proceed: "次の章に進んでください"
  pt:
    tagline: "Aprenda OpenStreetMap Passo-a-Passo"
    contribute: "Ajude-nos a melhorar os nossos guias!"
    trainingspan: "Você é um organizador do workshop?"
    training: "Confira material de treinamento para o novato guia (em Inglês)"
    feedbackspan: "Foi este capítulo foi útil?"
    feedback: "Conte-nos e ajudar-nos a melhorar os guias!"
    proceed: "prosseguir para o próximo capítulo"
  it:
    tagline: "Per saperne di OpenStreetMap Step-by-Step"
    contribute: "Aiutaci a migliorare le nostre guide!"
    trainingspan: "Sei un organizzatore del workshop?"
    training: "Scopri materiale di formazione per la guida principianti (in inglese)"
    feedbackspan: "Questa capitolo è stata utile?"
    feedback: "Fateci sapere e ci aiutano a migliorare le guide!"
    proceed: "procedere al capitolo successivo"