auto: true
pygments: true
server: true
markdown: rdiscount
permalink: /:categories/:title
columnist:
  paths:
  - _posts
baseurl: /learnosm
rdiscount:
  extensions: [smart]
translations:
  en:
    tagline: "Learn OpenStreetMap Step-by-Step"
    ourguides: "Our Guides"
    contribute: "Help us improve our guides!"
  es:
    tagline: "Aprende OpenStreetMap Paso a Paso"
    ourguides: "Nuestros Guías"
    contribute: "Nos ayudan a mejorar nuestros guías"
  bi:
    tagline:"Pelajari OpenStreetMap Langkah-Langkah"
    ourguides: "Pemandu Kami"
    contribute: "Bantu kami meningkatkan pemandu kami!"